import type { Metadata } from "next";
import { Inter,Roboto_Mono, Nunito,Bebas_Neue,Exo_2,Comfortaa,Varela_Round } from "next/font/google";
import "./globals.css";
import { Toaster as Sonner} from "@/components/ui/sonner";
import { Toaster as Toaster} from "@/components/ui/toaster"
import Loading from "@/components/my_componets/desktop/loading/Loading";
import { DialogLogOut } from "@/components/my_componets/desktop/dialogs/dialog_logout/DialogLogOut";
import Providers from "./providers";


const inter = Varela_Round({weight:"400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OnlineBank",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
      <html lang="en">
          <body className={inter.className} style={{padding:15}}>
            <main>
              <Providers attribute="class"
                defaultTheme="light"
                enableSystem
                disableTransitionOnChange
              >
                {children}
              </Providers>
            </main>
            <Sonner />
            <Toaster />
            <Loading/>
            <DialogLogOut/>
          </body>
      </html>
  );
}
