import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster as Sonner} from "@/components/ui/sonner";
import { Toaster as Toaster} from "@/components/ui/toaster"
import Loading from "@/components/my_componets/desktop/loading/Loading";
import { MyAlertDialog } from "@/components/my_componets/desktop/dialogs/alert_dialog/MyAlertDialog";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{padding:15}}>
        <main>
          {children}
        </main>
        <Sonner />
        <Toaster />
        <Loading/>
        <MyAlertDialog/>
      </body>
    </html>
  );
}
