import type { Metadata } from "next";
import style from './page.module.scss'
import SideBar from "@/components/my_componets/desktop/side_bar/SideBar";



export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section className={style.container}>
      <aside className={style.sideBar}>
        <SideBar/>
      </aside>
        <div className={style.container}>
          {children}
        </div>
      <footer className={style.footer}>
        footer
      </footer>
    </section>
  );
}
